# Experiment 3
Create a NumPy array with numbers from 1 to 12. Reshape it into a 3×4 matrix and display both arrays and their shapes.

In [1]:
import numpy as np

# Create array from 1 to 12
arr = np.arange(1, 13)

# Reshape to 3x4
reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Original Shape:", arr.shape)

print("\nReshaped Array:")
print(reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)
